// Generated by CoffeeScript 1.12.7
(function() {
  var Slack, _, request;

  request = require('request');

  _ = require('lodash');

  Slack = (function() {
    function Slack(incomingUrl, options1) {
      this.incomingUrl = incomingUrl;
      this.options = options1;
      this.validateArguments();
    }

    Slack.prototype.validateArguments = function() {
      if (this.incomingUrl == null) {
        throw new Error("Incoming url required");
      }
    };

    Slack.prototype.notify = function(message, callback) {
      var chn, count, i, len, options, ref, results, total;
      if ((message == null) || (_.isObject(message && ((message != null ? message.text : void 0) == null)))) {
        throw new Error('Message required');
      }
      options = {};
      options.text = typeof message === 'string' ? message : message.text;
      options.channel = message.channel == null ? '#general' : message.channel;
      options = _.extend(options, this.options);
      options = _.extend(options, message);
      if (_.isArray(options.channel)) {
        total = options.channel.length;
        count = 0;
        ref = options.channel;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          chn = ref[i];
          options.channel = chn;
          results.push(request.post(this.incomingUrl, {
            body: JSON.stringify(options)
          }, function(err, resp, body) {
            count++;
            if ((callback != null) && count === total) {
              if (body === 'ok') {
                return callback(null, body);
              } else {
                return callback(err || body);
              }
            }
          }));
        }
        return results;
      } else {
        return request.post(this.incomingUrl, {
          body: JSON.stringify(options)
        }, function(err, resp, body) {
          if (callback != null) {
            if (body === 'ok') {
              return callback(null, body);
            } else {
              return callback(err || body);
            }
          }
        });
      }
    };

    return Slack;

  })();

  module.exports = Slack;

}).call(this);
